### ISSUE TITLE
02:00 VVV is not available

### ISSUE THREAD

**Issue by hxxn85** [INU-NSS/Rhythm#14]
/dataserver/platforms/web.js - function calcSolRa
base_time 02:00 일 때, VVV 값이 없어서 계산 결과 NaN이 나옴

<img width="714" alt="image" src="https://user-images.githubusercontent.com/35563445/47310483-45c5b200-d672-11e8-9ba1-6874601ac96d.png">

**Comment by JOJAESEONG** [comment]
현재 2시때 파싱에 문제가 생기기 때문에 
basetime중에서 5 ,8 ,11, 14, 17, 20. 23 을 기준으로 
실제 사용은 8~23시만 사용할 예정으로 작업중입니다. ( 5시는 8시에 요청시 3시간의 온도차이를 위해서만 사용)
