### ISSUE TITLE
chart time problem

### ISSUE THREAD

**Issue by hxxn85** [INU-NSS/Rhythm#15]
03:20분에 차트 페이지 접속 시 00:00부터 03:20분까지 정보를 가져와서 출력해야 하는데,
전날 정보가 출력되고 있음.

timezone 문제로 보여짐

**Comment by JOJAESEONG** [comment]
현재 오전 01:22분 인데도 chart의 값은 현재 변함이 없습니다. 
query의 findday함수가 문제가 있는 것으로 보입니다. 

#17 에서의 time문제와 같다고 생각하여 날짜를 제대로 받아 올 수 있도록 수정할 계획입니다.

**Comment by JOJAESEONG** [comment]
chart가 9시 정도에 정상적으로 바뀌는 것으로 확인했습니다. 
날짜가 넘어가는게 #17 처럼 9시에 넘어가기 때문인 것을 현재는 원인으로 생각하고 있습니다.

**Comment by JOJAESEONG** [comment]
정확하게 9시에 그래프가 바뀌는 걸로 보아 #17 문제와 같습니다. 
timezone을 #17 처럼 수정하면 될 것 같습니다.

**Comment by JOJAESEONG** [comment]
현재 00시에 새로운 그래프로 나오는 것을 확인했습니다. 혹시나 하기 때문에 9시에 문제가 발생하는지 확인하겠습니다.

**Comment by JOJAESEONG** [comment]
오전 9시에도 데이터 값이 정확히 올라왔습니다.
timezone문제 해결됬습니다.
