### ISSUE TITLE
설정 관리

### ISSUE THREAD

**Issue by hxxn85** [INU-NSS/Rhythm#18]
설정 정보가 하드 코딩되어있음
- DB 접속 정보 (host, user, passwd, db 등)
- WEB 서버 포트 등등

[참조 및 공부에 도움이 되는 사이트](https://poiemaweb.com/nodejs-keeping-secrets)

**Comment by JOJAESEONG** [comment]
감사합니다 
확인해서 수정하겠습니다.

**Comment by JOJAESEONG** [comment]
현재 서버 포트 
db커넥션 , mqtt 커넥션, 소켓 커넥션, 웹서버 포트에 대한 config파일을 제작해서 적용시켜놨습니다. 

추가로 공공데이터의 key값도 중요정보이므로 config로 옮겨질 계획입니다.

@hxxn85 3단계 위에 있는 디렉토리를 require할때는 어떻게 해야되는지 모르겠습니다. 
두단계는 ../ 한단계는 ./ 인데 3단계는 어떻게 올려야 되나요?

**Comment by JOJAESEONG** [comment]
마지막으로 공공데이터 API의 KEY값들도 전부 config에 추가하여 github에 push해놨습니다.
